[platformio]
src_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  links2004/WebSockets @ ^2.6.1

[env:esp32dev]
board = esp32dev
build_src_filter =
  +<main.cpp>

[env:rgb_sensor_test]
board = esp32dev
build_src_filter =
  +<rgb_sensor_test.cpp>

[env:line_sensor_test]
board = esp32dev
build_src_filter =
  +<line_sensor_test.cpp>

[env:all_line_sensors_test]
board = esp32dev
build_src_filter =
  +<all_line_sensors_test.cpp>

[env:combined_sensor_test]
board = esp32dev
build_src_filter =
  +<combined_sensor_test.cpp>
