[platformio]
src_dir = .

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps =
  gilmaimon/ArduinoWebsockets @ ^0.5.4

[env:esp32dev]
board = esp32dev
build_src_filter =
  +<main.cpp>

[env:rgb_sensor_test]
board = esp32dev
build_src_filter =
  +<rgb_sensor_test.cpp>

[env:line_sensor_test]
board = esp32dev
build_src_filter =
  +<line_sensor_test.cpp>

[env:combined_sensor_test]
board = esp32dev
build_src_filter =
  +<combined_sensor_test.cpp>
